### PR TITLE
Supp

### PR DESCRIPTION
**Pull request by lmerchant**
I missed one more function call, supplemental_files, and added the raw and intermediate args to it.

When I did that, I noticed the if (raw) and if (intermediate) checks weren't working.  It's because raw and intermediate are arrays and an empty array is true.  If there are none of these files, then the first element of the array is undefined.  So I changed all checks to raw[0] and intermediate[0].

### CODE REVIEW

**Comment by DocOtak** [comment]
So I think these are still broken.

I think the `intermediate_files` and `raw_files` should be immediately called with the contents of `intermediate` and `raw`.  I think `(raw || intermediate)` test was relying on them having either content or being `undefined`. Really though, I don't remember how this was supposed to work.

Another issue is that even if they are working, there are no files for these methods to display. Have you done any testing (writing, running, etc) with javascript? I haven't... we might want to try it for this case.

**Comment by lmerchant** [comment]
If any files exist, then files is an array. I think for any cruise, files is an array, even if no files.  Then the raw variable applies the map function over each element of the array, but is still equal to an array.  An empty one.  So if there are no public raw files, the array is empty.  Since an empty array always defaults to true, the if condition is always true. It's a javascript thing. So that's why (raw || intermediate) won't ever evaluate to false.   I just choose to look for the first element of an empty array which would be undefined.  Probably should just check for array length instead, raw.length. 

And you're right, it's hard to check without any raw or intermediate files present.  So I duplicated the code for unprocessed files.  I changed Wespac from dataset to unprocessed for a check.  I pushed up the branch unpro that adds unprocessed files to supplemental files building on the last branch sup.  Looks to be working.



Lynne Merchant
lmerchant@ucsd.edu
CCHDO/SIO

**Comment by lmerchant** [comment]
OK, I checked using a cruises json file from https://cchdo.ucsd.edu/api/v1/pipe/site/microstructure.ucsd.edu <https://cchdo.ucsd.edu/api/v1/pipe/site/microstructure.ucsd.edu> and imported it locally into App.js.  I can then change roles to raw, intermediate, unprocessed, and along with adding multiple files for each role.

There are logic errors that I'll work on fixing.  The raw and intermediate variables are mapped over the files array.  And since files is an array, an array is always returned. In Javascript, you can't check for a true/false value on an array, even if empty, because an array is always true. 

If the files array is empty, then raw and intermediate = [].

If there is just one file, say a dataset file, files = [dataset] and raw = [undefined], intermediate = [undefined].

And if there are multiple files returned, say 3 files = [dataset, raw, inter], intermediate = [undefined, undefined, li elem], raw = [undefined, li elem, undefined]. 

So just needs some different logic to check if there are raw or intermediate files.  Let me see what I can do to fix it.

Lynne



Lynne Merchant
lmerchant@ucsd.edu
CCHDO/SIO

**Comment by lmerchant** [comment]
By switching from using map to reduce over the cruise files, the if check works by checking the raw or intermediate file arrays for length > 0.  And I added the raw and intermediate arguments to the supplemental_files call.

I added a branch called test where I imported a local cruise json file and modified the call to cruises in the cruise page section to use the local cruise file.  I didn't modify anything from master, so the supplemental_files call still needs arguments added to check things with it.  



Lynne Merchant
lmerchant@ucsd.edu
CCHDO/SIO

**Pull request closed without merging**
